### GET All users
GET http://localhost:3000/api/users


### GET user By Id
GET http://localhost:3000/api/users/5



### Create New user
POST http://localhost:3000/api/users
Content-Type:application/json

{
    "title":"product 5",
    "price":12
}


### Update user
PATCH  http://localhost:3000/api/users/1
Content-Type:application/json

{
    "title":"product 5",
    "price":12
}


### Delete Review
Delete  http://localhost:3000/api/users/1